name: Build and package bosto_house_prediction model to GitHub Packages

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

workflow_dispatch:

  jobs:
    build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Log in to the GH Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GH_REGISTRY }}


        - name: Build flask-app and push to GH registry
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: ./
            push: true
            tags: ghcr.io/davidemastricci/flask-boston-housing-prediction:latest
            